import { ACTIONS, createGame, step, seededRng, chooseUpgrade, getUpgrade, xpRequired } from './engine.js';
import { renderGame } from './renderer.js';
import { addGold, loadProgress, saveProgress, buyPermanent, permanentCosts } from './persistence.js';

const $ = id => document.getElementById(id);
let progress = loadProgress(), state = null, debug = false, locked = false, effects = [];
const directionKeys = { ArrowUp:'north', w:'north', W:'north', ArrowDown:'south', s:'south', S:'south', ArrowLeft:'west', a:'west', A:'west', ArrowRight:'east', d:'east', D:'east' };
const randomSeed = () => globalThis.crypto?.getRandomValues ? globalThis.crypto.getRandomValues(new Uint32Array(1))[0] : Math.floor(Math.random() * 2 ** 32);
const rng = () => seededRng((state?.seed || 1) + state?.turn * 7919 + state?.nextEntityId);
const render = () => {
  if (!state) return; renderGame($('board'), state, debug, effects); $('hp').textContent=`${state.player.hp}/${state.player.maxHp}`; $('level').textContent=state.player.level; $('xp').textContent=`${state.player.xp}/${xpRequired(state.player.level)}`; $('turn').textContent=state.turn; $('run-gold').textContent=state.runGold; $('facing').textContent=`Facing ${state.player.facing}`; $('debug-info').textContent=debug?`coords ${state.player.position.join(',')}\nRNG seed ${state.seed}\nentities ${state.nextEntityId}`:'';
};
const showBetween = () => { $('run').hidden=true; $('between').hidden=false; $('bank-gold').textContent=progress.gold; const shop=$('shop'); shop.replaceChildren(); const items=[['toughness','Toughness','+1 starting max HP'],['startingMagnet','Starting Magnet','+1 starting pickup range'],['sharpStart','Sharp Start','+1 starting Knife damage']]; for(const [id,name,desc] of items){const rank=progress.permanentUpgrades[id]||0,cost=permanentCosts[id]?.[rank];const button=document.createElement('button');button.disabled=cost==null||progress.gold<cost;button.innerHTML=`<span>${name} (rank ${rank})</span><small>${desc} · ${cost==null?'MAX':cost+' gold'}</small>`;button.onclick=()=>{progress=buyPermanent(progress,id);saveProgress(progress);showBetween();};shop.append(button);} };
const modal = (title,text,actions) => { $('modal-title').textContent=title; $('modal-text').textContent=text; const box=$('modal-actions');box.replaceChildren(); for(const a of actions){const b=document.createElement('button');b.className=a.primary?'primary':'ghost';b.innerHTML=a.html||a.label;b.onclick=()=>{ $('modal').hidden=true;a.run();};box.append(b);} $('modal').hidden=false; };
const showLevelUp = () => { const choices=state.pendingUpgradeChoices; modal('Level up!',`Choose one upgrade. Turn ${state.turn} is paused.`,choices.map(id=>{const u=getUpgrade(id);return {html:`<span class="upgrade-name">${u.name}</span><br><span class="upgrade-desc">${u.description}</span>`,primary:true,run:()=>{state=chooseUpgrade(state,id);render();}};})); };
const finishRun = () => { progress=addGold(progress,state.runGold);saveProgress(progress);showBetween(); };
const showEffects = events => { for (const event of events) { if (event.type === 'weapon-fired') { const effect = { type:'weapon-fired', weapon:event.weapon, direction:event.direction, cells:event.cells }; effects=[...effects,effect]; setTimeout(()=>{ effects=effects.filter(item=>item!==effect); render(); },260); } if (event.type === 'player-moved' || event.type === 'enemy-moved') { const effect = { type:'movement', entityId:event.enemyId ?? 'player', from:event.from, to:event.position }; effects=[...effects,effect]; setTimeout(()=>{ effects=effects.filter(item=>item!==effect); render(); },150); } if (event.type === 'player-damaged') { $('run').classList.remove('damage-flash'); void $('run').offsetWidth; $('run').classList.add('damage-flash'); setTimeout(()=>$('run').classList.remove('damage-flash'),220); } } };
const afterStep = result => { state=result.state; showEffects(result.events); render(); if(state.status==='level-up') showLevelUp(); else if(state.status==='victory') modal('Victory',`You survived turn ${state.turn}. Continue indefinitely or bank your ${state.runGold} gold.`,[{label:'Continue',primary:true,run:()=>{state=step(state,ACTIONS.continue,rng()).state;render();}},{label:'Exit Run',run:finishRun}]); else if(state.status==='dead') modal('Run ended',`The Red Squares overwhelmed you on turn ${state.turn}.`,[{label:'Return to camp',primary:true,run:finishRun}]); else if(state.status==='complete') finishRun(); };
const doAction = action => { if(!state||locked||state.status!=='playing')return; locked=true; afterStep(step(state,action,rng())); setTimeout(()=>locked=false,150); };
$('start').onclick=()=>{const seed=Number($('seed').value)||randomSeed();effects=[];state=createGame({seed,permanent:progress.permanentUpgrades});$('between').hidden=true;$('run').hidden=false;render();};
$('exit').onclick=()=>{if(state)finishRun();};
$('debug').onclick=()=>{debug=!debug;render();};
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const [type,direction]=button.dataset.action.split(':');doAction(direction?type==='move'?ACTIONS.move(direction):ACTIONS.waitFacing(direction):ACTIONS.wait);});
document.querySelectorAll('[data-face]').forEach(button=>button.onclick=()=>doAction(ACTIONS.waitFacing(button.dataset.face)));
document.addEventListener('keydown',event=>{if($('modal').hidden===false)return;const d=directionKeys[event.key];if(d){event.preventDefault();doAction(event.shiftKey?ACTIONS.waitFacing(d):ACTIONS.move(d));}else if(event.key===' '){event.preventDefault();doAction(ACTIONS.wait);}});
showBetween();
