import { ACTIONS, createGame, step, seededRng, getUpgrade, xpRequired } from './engine.js';
import { PERMANENT_UPGRADE_DEFINITIONS, WEAPON_DEFINITIONS } from './config.js';
import { renderGame } from './renderer.js';
import { addGold, loadProgress, saveProgress, buyPermanent, permanentCosts } from './persistence.js';

const $ = id => document.getElementById(id);
let progress = loadProgress(), state = null, debug = false, effects = [], runGeneration = 0, startingWeapon = 'knife';
const directionKeys = { ArrowUp:'north', w:'north', W:'north', ArrowDown:'south', s:'south', S:'south', ArrowLeft:'west', a:'west', A:'west', ArrowRight:'east', d:'east', D:'east' };
const randomSeed = () => globalThis.crypto?.getRandomValues ? globalThis.crypto.getRandomValues(new Uint32Array(1))[0] : Math.floor(Math.random() * 2 ** 32);
const rng = () => seededRng((state?.seed || 1) + state?.turn * 7919 + state?.nextEntityId);
const render = () => {
  if (!state) return; renderGame($('board'), state, debug, effects); $('hp').textContent=`${state.player.hp}/${state.player.maxHp}`; $('level').textContent=state.player.level; $('xp').textContent=`${state.player.xp}/${xpRequired(state.player.level)}`; $('turn').textContent=state.turn; $('run-gold').textContent=state.runGold; $('facing').textContent=`Facing ${state.player.facing}`; $('debug-info').textContent=debug?`coords ${state.player.position.join(',')}\nRNG seed ${state.seed}\nentities ${state.nextEntityId}`:'';
};
const renderStartingWeapons = () => { const container=$('starting-weapons'); container.replaceChildren(); const options=[{type:'knife',unlockId:null},...PERMANENT_UPGRADE_DEFINITIONS.filter(definition=>definition.operation?.kind==='starting-weapon').map(definition=>({type:definition.operation.weaponType,unlockId:definition.id}))]; for(const option of options){const definition=WEAPON_DEFINITIONS[option.type],rank=option.unlockId?progress.permanentUpgrades[option.unlockId]||0:0,cost=option.unlockId?permanentCosts[option.unlockId]?.[rank]:null,unlocked=!option.unlockId||rank>0,canUnlock=!unlocked&&progress.gold>=cost,card=document.createElement('button');card.type='button';card.className=`weapon-card${option.type===startingWeapon&&unlocked?' selected':''}${unlocked?'':' locked'}${canUnlock?' unlockable':''}`;card.disabled=!unlocked&&!canUnlock;card.style.setProperty('--weapon-color',definition.effectColor);card.setAttribute('aria-pressed',String(option.type===startingWeapon&&unlocked));const icon=document.createElement('span');icon.className='weapon-icon';icon.textContent=definition.icon;const content=document.createElement('span');content.className='weapon-card-content';const name=document.createElement('strong');name.textContent=definition.name;const description=document.createElement('small');description.textContent=unlocked?definition.description:canUnlock?`Unlock for ${cost} gold`:`Need ${cost} gold to unlock`;const cadence=document.createElement('small');cadence.className='weapon-cadence';cadence.textContent=unlocked?`Every ${definition.period} turns`:'Permanent unlock';content.append(name,description,cadence);card.append(icon,content);card.onclick=()=>{if(!unlocked){progress=buyPermanent(progress,option.unlockId);saveProgress(progress);showBetween();}else{startingWeapon=option.type;renderStartingWeapons();}};container.append(card);} $('starting-weapon-status').textContent=`${WEAPON_DEFINITIONS[startingWeapon].name} selected`; };
const showBetween = () => { $('run').hidden=true; $('between').hidden=false; $('bank-gold').textContent=progress.gold; const shop=$('shop'); shop.replaceChildren(); for(const {id,name,description} of PERMANENT_UPGRADE_DEFINITIONS.filter(definition=>definition.operation?.kind!=='starting-weapon')){const rank=progress.permanentUpgrades[id]||0,cost=permanentCosts[id]?.[rank];const button=document.createElement('button');button.disabled=cost==null||progress.gold<cost;const title=document.createElement('span');title.textContent=`${name} (rank ${rank})`;const detail=document.createElement('small');detail.textContent=`${description} · ${cost==null?'MAX':cost+' gold'}`;button.append(title,detail);button.onclick=()=>{progress=buyPermanent(progress,id);saveProgress(progress);showBetween();};shop.append(button);} if(!WEAPON_DEFINITIONS[startingWeapon]) startingWeapon='knife'; renderStartingWeapons(); };
const modal = (title,text,actions) => { $('modal-title').textContent=title; $('modal-text').textContent=text; const box=$('modal-actions');box.replaceChildren(); for(const a of actions){const b=document.createElement('button');b.className=a.primary?'primary':'ghost';if(a.title){const name=document.createElement('span');name.className='upgrade-name';name.textContent=a.title;const description=document.createElement('span');description.className='upgrade-desc';description.textContent=a.description;b.append(name,document.createElement('br'),description);}else b.textContent=a.label;b.onclick=()=>{ $('modal').hidden=true;a.run();};box.append(b);} $('modal').hidden=false; };
const showLevelUp = () => { const choices=state.pendingUpgradeChoices; modal('Level up!',`Choose one upgrade. Turn ${state.turn} is paused.`,choices.map(id=>{const u=getUpgrade(id);return {title:u.name,description:u.description,primary:true,run:()=>afterStep(step(state,ACTIONS.selectUpgrade(id),rng()))};})); };
const finishRun = () => { runGeneration += 1; progress=addGold(progress,state.runGold);saveProgress(progress);showBetween(); };
const addEffect = (effect, duration) => { const generation = runGeneration; effects=[...effects,effect]; setTimeout(()=>{ if (generation !== runGeneration) return; effects=effects.filter(item=>item!==effect); render(); },duration); };
const showEffects = events => { for (const event of events) { if (event.type === 'weapon-fired') addEffect({ type:'weapon-fired', weapon:event.weapon, direction:event.direction, cells:event.cells },260); if (event.type === 'player-moved' || event.type === 'enemy-moved') addEffect({ type:'movement-trail', entityId:event.enemyId ?? 'player', from:event.from, to:event.position },350); if (event.type === 'player-damaged') { $('run').classList.remove('damage-flash'); void $('run').offsetWidth; $('run').classList.add('damage-flash'); setTimeout(()=>$('run').classList.remove('damage-flash'),220); } } };
const afterStep = result => { state=result.state; showEffects(result.events); render(); if(state.status==='level-up') showLevelUp(); else if(state.status==='victory') modal('Victory',`You survived turn ${state.turn}. Continue indefinitely or bank your ${state.runGold} gold.`,[{label:'Continue',primary:true,run:()=>{state=step(state,ACTIONS.continue,rng()).state;render();}},{label:'Exit Run',run:finishRun}]); else if(state.status==='dead') modal('Run ended',`The Red Squares overwhelmed you on turn ${state.turn}.`,[{label:'Return to camp',primary:true,run:finishRun}]); else if(state.status==='complete') finishRun(); };
const doAction = action => { if(!state||state.status!=='playing')return; afterStep(step(state,action,rng())); };
$('start').onclick=()=>{const seed=Number($('seed').value)||randomSeed();runGeneration += 1;effects=[];state=createGame({seed,permanent:progress.permanentUpgrades,startingWeapon});$('between').hidden=true;$('run').hidden=false;render();};
$('exit').onclick=()=>{if(state)finishRun();};
$('debug').onclick=()=>{debug=!debug;render();};
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const [type,direction]=button.dataset.action.split(':');doAction(direction?type==='move'?ACTIONS.move(direction):ACTIONS.waitFacing(direction):ACTIONS.wait);});
document.querySelectorAll('[data-face]').forEach(button=>button.onclick=()=>doAction(ACTIONS.waitFacing(button.dataset.face)));
document.addEventListener('keydown',event=>{if($('modal').hidden===false)return;const d=directionKeys[event.key];if(d){event.preventDefault();doAction(event.shiftKey?ACTIONS.waitFacing(d):ACTIONS.move(d));}else if(event.key===' '){event.preventDefault();doAction(ACTIONS.wait);}});
showBetween();
