import { terrainAt } from './engine.js';
import { VIEWPORT_RADIUS } from './engine/constants.js';
import { ENEMY_DEFINITIONS, WEAPON_DEFINITIONS } from './config.js';
const NS = 'http://www.w3.org/2000/svg';
const svgEl = (tag, attrs = {}) => { const e = document.createElementNS(NS, tag); for (const [k,v] of Object.entries(attrs)) e.setAttribute(k, v); return e; };
const color = { floor: '#151c2d', wall: '#4d5a70' };
const inViewport = (position, playerPosition, radius = VIEWPORT_RADIUS + 1) => Math.abs(position[0] - playerPosition[0]) <= radius && Math.abs(position[1] - playerPosition[1]) <= radius;
const weaponPoints = (x, y, direction) => ({ north:`${x+2},${y+10} ${x+6},${y+2} ${x+10},${y+10}`, south:`${x+2},${y+2} ${x+6},${y+10} ${x+10},${y+2}`, east:`${x+2},${y+2} ${x+10},${y+6} ${x+2},${y+10}`, west:`${x+10},${y+2} ${x+2},${y+6} ${x+10},${y+10}` })[direction] || `${x+2},${y+2} ${x+10},${y+6} ${x+2},${y+10}`;
export const renderGame = (svg, state, debug = false, effects = []) => {
  svg.replaceChildren(); const size = 12, half = VIEWPORT_RADIUS, renderRadius = VIEWPORT_RADIUS + 1, dimension = renderRadius * 2 + 1, cameraMovement = effects.find(effect => effect.type === 'movement' && effect.entityId === 'player'), world = svgEl('g', cameraMovement ? { class: 'camera-movement', style: `--camera-x:${(cameraMovement.to[0] - cameraMovement.from[0]) * size}px;--camera-y:${(cameraMovement.to[1] - cameraMovement.from[1]) * size}px` } : {}), worldContent = svgEl('g', { transform: `translate(${(half - state.player.position[0]) * size},${(half - state.player.position[1]) * size})` }), playerLayer = svgEl('g'); svg.append(world, playerLayer); world.append(worldContent); svg.setAttribute('viewBox', `0 0 ${size*(half*2+1)} ${size*(half*2+1)}`);
  const [px,py] = state.player.position;
  for (let row=0; row<dimension; row++) for (let col=0; col<dimension; col++) { const x=px+col-renderRadius, y=py+row-renderRadius; const tile=svgEl('rect',{x:x*size,y:y*size,width:size-0.5,height:size-0.5,fill:color[terrainAt(state.map,x,y)]}); worldContent.append(tile); }
  const at = p => [p[0]*size, p[1]*size];
  for (const object of state.breakables) if (inViewport(object.position,state.player.position)) { const [x,y]=at(object.position); worldContent.append(svgEl('rect',{x:x+2,y:y+2,width:8,height:8,fill:'none',stroke:'#d9a441','stroke-width':2,rx:2})); }
  for (const pickup of state.pickups) if (inViewport(pickup.position,state.player.position)) { const [x,y]=at(pickup.position); if(pickup.type==='xp') worldContent.append(svgEl('polygon',{points:`${x+6},${y+2} ${x+10},${y+6} ${x+6},${y+10} ${x+2},${y+6}`,fill:'#62d6ff'})); else if (pickup.type === 'health') worldContent.append(svgEl('path',{d:'M4 0h4v4h4v4H8v4H4v-4H0V4h4z',transform:`translate(${x},${y})`,fill:'#67e58b'})); else worldContent.append(svgEl('circle',{cx:x+6,cy:y+6,r:4,fill:'#ffd166',stroke:'#fff0a8','stroke-width':1})); }
  const movementAttrs = entityId => { const movement = effects.find(effect => effect.type === 'movement' && effect.entityId === entityId); if (!movement) return {}; return { class: 'movement-animation', style: `--move-x:${(movement.from[0] - movement.to[0]) * size}px;--move-y:${(movement.from[1] - movement.to[1]) * size}px` }; };
  for (const enemy of state.enemies) { if(!inViewport(enemy.position,state.player.position)) continue; const [x,y]=at(enemy.position); const definition = ENEMY_DEFINITIONS[enemy.type] ?? ENEMY_DEFINITIONS['red-square']; const shape = definition.shape === 'circle' ? svgEl('circle',{cx:x+6,cy:y+6,r:5,fill:definition.color,...movementAttrs(enemy.id)}) : svgEl('rect',{x:x+1,y:y+1,width:10,height:10,fill:definition.color,rx:2,...movementAttrs(enemy.id)}); worldContent.append(shape); if(debug){const t=svgEl('text',{x:x+1,y:y+9,fill:'white','font-size':5});t.textContent=enemy.id;worldContent.append(t);} }
  const x=half*size, y=half*size; const player=svgEl('circle',{cx:x+6,cy:y+6,r:4.5,fill:'#f4f7ff',stroke:'#7c5cff','stroke-width':2}); playerLayer.append(player); const [dx,dy] = ({north:[0,-3],south:[0,3],east:[3,0],west:[-3,0]})[state.player.facing]; playerLayer.append(svgEl('line',{x1:x+6,y1:y+6,x2:x+6+dx,y2:y+6+dy,stroke:'#ffcf5a','stroke-width':2}));
  for (const e of effects) { if (e.type !== 'weapon-fired') continue; const pts=e.cells.map(c=>at(c)); const definition = WEAPON_DEFINITIONS[e.weapon] ?? WEAPON_DEFINITIONS.knife; for(const [ex,ey] of pts) worldContent.append(svgEl('polygon',{points:weaponPoints(ex,ey,e.direction),fill:definition.effectColor,opacity:.85,class:'weapon-effect'})); }
};
